spring:
  application:
    name: azure-rest-api-guidelines

  jpa:
    hibernate:
      # Automatically create database tables based on entity definitions
      ddl-auto: create
    # Defer the database population until after hibernate created the schema
    defer-datasource-initialization: true

  # Enable In-Memory Caching
  cache:
    cache-names: "REPEATABILITY_CACHE"
    redis:
      time-to-live: "5m"